site_name: androidrest
site_description: Demo Rest
repo_url: https://github.com/hernanramirez/android-rest
site_dir: site
copyright: Copyright &copy; 2015, <a href="https://github.com/hernanramirez">hernanramirez</a>.

pages:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
